name: TerraformCI/CD

on:
  push:
    branches:
      - AzureTerraform_Branch

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      # Azure login gamit ang SP credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform commands
      - run: terraform init
      - run: terraform validate
      - run: terraform plan

      # 👉 Import step bago mag-apply
      - name: Import existing RG
        run: terraform import azurerm_resource_group.RG_Terraform /subscriptions/53e398b6-1041-4cce-a9bf-f3b167986a4c/resourceGroups/demo-rg

      - run: terraform apply -auto-approve
