name: TerraformCI/CD

on:
  push:
    branches:
      - AzureTerraform_Branch

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      # Azure login gamit ang SP credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform commands
      - run: terraform init
      - run: terraform validate
      - run: terraform plan

      - run: terraform apply -auto-approve
